### ISSUE TITLE
Inappropriate use of `.h` files for implementation

### ISSUE THREAD

**Issue by ricardotaborda** [ProgTools2017HeatGroup/2D-Heat-Convection-by-FDM#37]
`.h` files should not be used for implementing functions, but simply to declare prototypes and data structures. The file `calculate_velocity.h` has full implementation of the functions `set_omega` and `set_psi`. This is inappropriate.

**Comment by alarshi** [comment]
Fixed

**Comment by ricardotaborda** [comment]
This problem also occurs in other files. Fix it in all `.h` files. In general, `.h` files are not supposed to have code implementations but only prototypes and definitions.

**Comment by ricardotaborda** [comment]
The problem persists in...

* `initial_temp.h`
* `set_density.h`

**Comment by alarshi** [comment]
Fixed in all headers, thank you.
